version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=photo_portfolio.settings
    command: python manage.py runserver 0.0.0.0:8010

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: jh777
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: galeria_db
    ports:
      - "5432:5432"  
volumes:
  postgres_data: