# Generated by Django 5.1.2 on 2024-11-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
    ]
